### ISSUE TITLE
Remove prefixes from function in dkmeans_*_computations

### ISSUE THREAD

**Issue by everner-ds** [MRN-Code/dkmeans#13]
I recommend removing the ```dkm_local_``` prefix from all of these functions. The reader should be able to tell from the name of the module that these are all dkmeans local computations. You can change the import statement in dkmeans_multishot to:

```python
import dkmeans_local_computations as dkm_local
```

Then you can call your functions later as:

```python
dkm_local.compute_mean()
dkm_local.gradient_step()
```
This will allow you to convey the same information in a less verbose way.

**Comment by bbradt** [comment]
resolved by https://github.com/MRN-Code/dkmeans/commit/36e5a45a6f9d840533216ba27357fdf3207786cb
