### ISSUE TITLE
Make a leaner branch of the repository

### ISSUE THREAD

**Issue by everner-ds** [MRN-Code/dkmeans#8]
Although I think the ipython notebook, results, and gifs are useful in understanding the code and saving and displaying results, we may want to create a branch that will be used specifically for creation of the Docker container that will be used in the real COINSTAC application.

**Comment by bbradt** [comment]
Closed by commit 0e7955e42357fd37dee86ce28fb5d9823f1a220b.
I stripped the directory to just the README, License, Requirements.txt, and python files required for running. 
The full repo can be readded as a separate branch, or as a separate repository if desired.
